# Generated by Django 4.2.4 on 2023-08-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'DECLINED')], default=0),
        ),
    ]
