# Generated by Django 4.2.4 on 2023-08-04 02:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_like_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('photo', 'user')},
        ),
    ]
